---
build-package:
  stage: deploy
  only:
    - tags
  image: python:3.8
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - pip install twine
    - python setup.py  bdist_wheel
    - python -m twine upload --repository pypi dist/pymindergas-${CI_COMMIT_TAG}* --config-file /tmp/.pypirc
    # - python -m twine upload --repository testpypi dist/pymindergas-${CI_COMMIT_TAG}* --config-file /tmp/.pypirc
    - python -m twine upload --repository gitlab dist/pymindergas-${CI_COMMIT_TAG}* --config-file /tmp/.pypirc
